[theme]
primaryColor="#00C853"          # hijau terang
backgroundColor="#ffffff"       # putih
secondaryBackgroundColor="#e8f5e9" # hijau muda banget
textColor="#000000"             # hitam
font="sans serif"